version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=twoje_haslo
      - GENERIC_TIMEZONE=Europe/Warsaw
      - TZ=Europe/Warsaw
      - N8N_CUSTOM_EXTENSIONS=/custom-nodes
    volumes:
      - n8n_data:/home/node/.n8n
      - ./packages/n8n-nodes-ceidg:/custom-nodes/node_modules/n8n-nodes-ceidg
      - ./packages/n8n-nodes-smsapi:/custom-nodes/node_modules/n8n-nodes-smsapi
      - ./packages/n8n-nodes-fakturownia:/custom-nodes/node_modules/n8n-nodes-fakturownia
      - ./packages/n8n-nodes-linkercloud:/custom-nodes/node_modules/n8n-nodes-linkercloud
      - ./packages/n8n-nodes-nbp:/custom-nodes/node_modules/n8n-nodes-nbp
      - ./packages/n8n-nodes-biala-lista-vat:/custom-nodes/node_modules/n8n-nodes-biala-lista-vat
      - ./packages/n8n-nodes-ceneo:/custom-nodes/node_modules/n8n-nodes-ceneo
      - ./packages/n8n-nodes-gus-regon:/custom-nodes/node_modules/n8n-nodes-gus-regon
      - ./packages/n8n-nodes-krs:/custom-nodes/node_modules/n8n-nodes-krs
      - ./packages/n8n-nodes-nfz:/custom-nodes/node_modules/n8n-nodes-nfz
      - ./packages/n8n-nodes-vies:/custom-nodes/node_modules/n8n-nodes-vies
      - ./packages/n8n-nodes-inpost:/custom-nodes/node_modules/n8n-nodes-inpost

volumes:
  n8n_data:
