import type { INodeProperties } from 'n8n-workflow';

export const productOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: {
		show: {
			resource: ['product'],
		},
	},
	options: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a product',
			description: 'Create a new product in the catalog',
		},
		{
			name: 'List',
			value: 'list',
			action: 'List products',
			description: 'Get a list of products',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a product',
			description: 'Update an existing product',
		},
	],
	default: 'list',
};

export const productFields: INodeProperties[] = [
	// ------ Product ID (update) ------
	{
		displayName: 'Product ID',
		name: 'productId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the product to update',
		displayOptions: {
			show: {
				resource: ['product'],
				operation: ['update'],
			},
		},
	},

	// ------ Return All (list) ------
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: {
			show: {
				resource: ['product'],
				operation: ['list'],
			},
		},
	},

	// ------ Limit (list, when returnAll=false) ------
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: {
				resource: ['product'],
				operation: ['list'],
				returnAll: [false],
			},
		},
	},

	// ------ Name (create, required) ------
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		description: 'Product name',
		displayOptions: {
			show: {
				resource: ['product'],
				operation: ['create'],
			},
		},
	},

	// ------ SKU (create, required) ------
	{
		displayName: 'SKU',
		name: 'sku',
		type: 'string',
		required: true,
		default: '',
		description: 'Stock Keeping Unit code',
		displayOptions: {
			show: {
				resource: ['product'],
				operation: ['create'],
			},
		},
	},

	// ------ Additional Fields (create) ------
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['product'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Always Ask for Serial Number',
				name: 'always_ask_for_serial_number',
				type: 'boolean',
				default: false,
				description: 'Whether to always ask for serial number during warehouse operations',
			},
			{
				displayName: 'Barcode',
				name: 'barcode',
				type: 'string',
				default: '',
				description: 'Product barcode (EAN)',
			},
			{
				displayName: 'Box Depth',
				name: 'boxDepth',
				type: 'string',
				default: '',
				description: 'Box/carton depth',
			},
			{
				displayName: 'Box Length',
				name: 'boxLength',
				type: 'string',
				default: '',
				description: 'Box/carton length',
			},
			{
				displayName: 'Box Weight',
				name: 'boxWeight',
				type: 'string',
				default: '',
				description: 'Box/carton gross weight',
			},
			{
				displayName: 'Box Width',
				name: 'boxWidth',
				type: 'string',
				default: '',
				description: 'Box/carton width',
			},
			{
				displayName: 'Category',
				name: 'category',
				type: 'string',
				default: '',
				description: 'Product category',
			},
			{
				displayName: 'Country of Origin',
				name: 'country_of_origin',
				type: 'string',
				default: '',
				description: 'Country of origin (ISO 3166-2, e.g. PL, CN)',
			},
			{
				displayName: 'Depth',
				name: 'depth',
				type: 'string',
				default: '',
				description: 'Product depth',
			},
			{
				displayName: 'Depot ID',
				name: 'depotId',
				type: 'string',
				default: '',
				description: 'ID of the depot/warehouse',
			},
			{
				displayName: 'Dimensions Unit',
				name: 'dimensionsUnit',
				type: 'string',
				default: '',
				description: 'Unit for dimensions (e.g. mm, cm)',
			},
			{
				displayName: 'External ID',
				name: 'externalId',
				type: 'string',
				default: '',
				description: 'External system ID',
			},
			{
				displayName: 'Harmonized System Code',
				name: 'harmonized_system_code',
				type: 'string',
				default: '',
				description: 'HS/CN code for customs (e.g. 6109100010)',
			},
			{
				displayName: 'Has Batch Number',
				name: 'has_batch_number',
				type: 'boolean',
				default: false,
				description: 'Whether the product uses batch numbers',
			},
			{
				displayName: 'Height',
				name: 'height',
				type: 'string',
				default: '',
				description: 'Product height',
			},
			{
				displayName: 'Ignore in WMS',
				name: 'ignore_in_wms',
				type: 'boolean',
				default: false,
				description: 'Whether to ignore this product in WMS operations',
			},
			{
				displayName: 'Ignore When Packing',
				name: 'ignore_when_packing',
				type: 'boolean',
				default: false,
				description: 'Whether to ignore this product during packing',
			},
			{
				displayName: 'Is Bio',
				name: 'is_bio',
				type: 'boolean',
				default: false,
				description: 'Whether the product is a bio/organic product',
			},
			{
				displayName: 'Is Expirable',
				name: 'is_expirable',
				type: 'boolean',
				default: false,
				description: 'Whether the product has an expiration date',
			},
			{
				displayName: 'Is Food',
				name: 'is_food',
				type: 'boolean',
				default: false,
				description: 'Whether the product is a food item',
			},
			{
				displayName: 'Is Fragile',
				name: 'is_fragile',
				type: 'boolean',
				default: false,
				description: 'Whether the product is fragile and requires careful handling',
			},
			{
				displayName: 'Is Insert',
				name: 'is_insert',
				type: 'boolean',
				default: false,
				description: 'Whether the product is an insert (marketing material added to packages)',
			},
			{
				displayName: 'Layer Depth',
				name: 'layerDepth',
				type: 'string',
				default: '',
				description: 'Pallet layer depth',
			},
			{
				displayName: 'Layer Length',
				name: 'layerLength',
				type: 'string',
				default: '',
				description: 'Pallet layer length',
			},
			{
				displayName: 'Layer Net Weight',
				name: 'layerNetWeight',
				type: 'string',
				default: '',
				description: 'Pallet layer net weight',
			},
			{
				displayName: 'Layer Weight',
				name: 'layerWeight',
				type: 'string',
				default: '',
				description: 'Pallet layer gross weight',
			},
			{
				displayName: 'Layer Width',
				name: 'layerWidth',
				type: 'string',
				default: '',
				description: 'Pallet layer width',
			},
			{
				displayName: 'Length',
				name: 'length',
				type: 'string',
				default: '',
				description: 'Product length',
			},
			{
				displayName: 'Minimal Stock',
				name: 'minimalStock',
				type: 'string',
				default: '',
				description: 'Minimum stock level threshold',
			},
			{
				displayName: 'Net Box Weight',
				name: 'netBoxWeight',
				type: 'string',
				default: '',
				description: 'Box/carton net weight',
			},
			{
				displayName: 'Net Weight',
				name: 'netWeight',
				type: 'string',
				default: '',
				description: 'Product net weight',
			},
			{
				displayName: 'Province of Origin',
				name: 'province_of_origin',
				type: 'string',
				default: '',
				description: 'Province/region of origin',
			},
			{
				displayName: 'Storehouse Location',
				name: 'storehouse_location',
				type: 'string',
				default: '',
				description: 'Storehouse/shelf location code',
			},
			{
				displayName: 'Unit',
				name: 'unit',
				type: 'string',
				default: '',
				description: 'Unit of measure (e.g. pcs, kg, m)',
			},
			{
				displayName: 'Volume',
				name: 'volume',
				type: 'string',
				default: '',
				description: 'Product volume',
			},
			{
				displayName: 'Volume Unit',
				name: 'volumeUnit',
				type: 'string',
				default: '',
				description: 'Unit for volume (e.g. ml, l, cm3)',
			},
			{
				displayName: 'Weight',
				name: 'weight',
				type: 'string',
				default: '',
				description: 'Product gross weight',
			},
			{
				displayName: 'Weight Unit',
				name: 'weightUnit',
				type: 'string',
				default: '',
				description: 'Unit for weight (e.g. g, kg)',
			},
			{
				displayName: 'Width',
				name: 'width',
				type: 'string',
				default: '',
				description: 'Product width',
			},
			{
				displayName: 'WMS External ID',
				name: 'wms_external_id',
				type: 'string',
				default: '',
				description: 'WMS system external ID',
			},
		],
	},

	// ------ Update Fields (update) ------
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['product'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Always Ask for Serial Number',
				name: 'always_ask_for_serial_number',
				type: 'boolean',
				default: false,
				description: 'Whether to always ask for serial number during warehouse operations',
			},
			{
				displayName: 'Barcode',
				name: 'barcode',
				type: 'string',
				default: '',
				description: 'Product barcode (EAN)',
			},
			{
				displayName: 'Box Depth',
				name: 'boxDepth',
				type: 'string',
				default: '',
				description: 'Box/carton depth',
			},
			{
				displayName: 'Box Length',
				name: 'boxLength',
				type: 'string',
				default: '',
				description: 'Box/carton length',
			},
			{
				displayName: 'Box Weight',
				name: 'boxWeight',
				type: 'string',
				default: '',
				description: 'Box/carton gross weight',
			},
			{
				displayName: 'Box Width',
				name: 'boxWidth',
				type: 'string',
				default: '',
				description: 'Box/carton width',
			},
			{
				displayName: 'Category',
				name: 'category',
				type: 'string',
				default: '',
				description: 'Product category',
			},
			{
				displayName: 'Country of Origin',
				name: 'country_of_origin',
				type: 'string',
				default: '',
				description: 'Country of origin (ISO 3166-2)',
			},
			{
				displayName: 'Depth',
				name: 'depth',
				type: 'string',
				default: '',
				description: 'Product depth',
			},
			{
				displayName: 'Depot ID',
				name: 'depotId',
				type: 'string',
				default: '',
				description: 'ID of the depot/warehouse',
			},
			{
				displayName: 'Dimensions Unit',
				name: 'dimensionsUnit',
				type: 'string',
				default: '',
				description: 'Unit for dimensions (e.g. mm, cm)',
			},
			{
				displayName: 'External ID',
				name: 'externalId',
				type: 'string',
				default: '',
				description: 'External system ID',
			},
			{
				displayName: 'Harmonized System Code',
				name: 'harmonized_system_code',
				type: 'string',
				default: '',
				description: 'HS/CN code for customs',
			},
			{
				displayName: 'Has Batch Number',
				name: 'has_batch_number',
				type: 'boolean',
				default: false,
				description: 'Whether the product uses batch numbers',
			},
			{
				displayName: 'Height',
				name: 'height',
				type: 'string',
				default: '',
				description: 'Product height',
			},
			{
				displayName: 'Ignore in WMS',
				name: 'ignore_in_wms',
				type: 'boolean',
				default: false,
				description: 'Whether to ignore this product in WMS operations',
			},
			{
				displayName: 'Ignore When Packing',
				name: 'ignore_when_packing',
				type: 'boolean',
				default: false,
				description: 'Whether to ignore this product during packing',
			},
			{
				displayName: 'Is Bio',
				name: 'is_bio',
				type: 'boolean',
				default: false,
				description: 'Whether the product is a bio/organic product',
			},
			{
				displayName: 'Is Expirable',
				name: 'is_expirable',
				type: 'boolean',
				default: false,
				description: 'Whether the product has an expiration date',
			},
			{
				displayName: 'Is Food',
				name: 'is_food',
				type: 'boolean',
				default: false,
				description: 'Whether the product is a food item',
			},
			{
				displayName: 'Is Fragile',
				name: 'is_fragile',
				type: 'boolean',
				default: false,
				description: 'Whether the product is fragile and requires careful handling',
			},
			{
				displayName: 'Is Insert',
				name: 'is_insert',
				type: 'boolean',
				default: false,
				description: 'Whether the product is an insert (marketing material added to packages)',
			},
			{
				displayName: 'Layer Depth',
				name: 'layerDepth',
				type: 'string',
				default: '',
				description: 'Pallet layer depth',
			},
			{
				displayName: 'Layer Length',
				name: 'layerLength',
				type: 'string',
				default: '',
				description: 'Pallet layer length',
			},
			{
				displayName: 'Layer Net Weight',
				name: 'layerNetWeight',
				type: 'string',
				default: '',
				description: 'Pallet layer net weight',
			},
			{
				displayName: 'Layer Weight',
				name: 'layerWeight',
				type: 'string',
				default: '',
				description: 'Pallet layer gross weight',
			},
			{
				displayName: 'Layer Width',
				name: 'layerWidth',
				type: 'string',
				default: '',
				description: 'Pallet layer width',
			},
			{
				displayName: 'Length',
				name: 'length',
				type: 'string',
				default: '',
				description: 'Product length',
			},
			{
				displayName: 'Minimal Stock',
				name: 'minimalStock',
				type: 'string',
				default: '',
				description: 'Minimum stock level threshold',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Product name',
			},
			{
				displayName: 'Net Box Weight',
				name: 'netBoxWeight',
				type: 'string',
				default: '',
				description: 'Box/carton net weight',
			},
			{
				displayName: 'Net Weight',
				name: 'netWeight',
				type: 'string',
				default: '',
				description: 'Product net weight',
			},
			{
				displayName: 'Province of Origin',
				name: 'province_of_origin',
				type: 'string',
				default: '',
				description: 'Province/region of origin',
			},
			{
				displayName: 'SKU',
				name: 'sku',
				type: 'string',
				default: '',
				description: 'Stock Keeping Unit code',
			},
			{
				displayName: 'Storehouse Location',
				name: 'storehouse_location',
				type: 'string',
				default: '',
				description: 'Storehouse/shelf location code',
			},
			{
				displayName: 'Unit',
				name: 'unit',
				type: 'string',
				default: '',
				description: 'Unit of measure (e.g. pcs, kg, m)',
			},
			{
				displayName: 'Volume',
				name: 'volume',
				type: 'string',
				default: '',
				description: 'Product volume',
			},
			{
				displayName: 'Volume Unit',
				name: 'volumeUnit',
				type: 'string',
				default: '',
				description: 'Unit for volume (e.g. ml, l, cm3)',
			},
			{
				displayName: 'Weight',
				name: 'weight',
				type: 'string',
				default: '',
				description: 'Product gross weight',
			},
			{
				displayName: 'Weight Unit',
				name: 'weightUnit',
				type: 'string',
				default: '',
				description: 'Unit for weight (e.g. g, kg)',
			},
			{
				displayName: 'Width',
				name: 'width',
				type: 'string',
				default: '',
				description: 'Product width',
			},
			{
				displayName: 'WMS External ID',
				name: 'wms_external_id',
				type: 'string',
				default: '',
				description: 'WMS system external ID',
			},
		],
	},
];
